FROM python:3.8.13-slim-buster

#Install packages
RUN apt-get update && apt-get install -y libgomp1 curl

# Installing google-cloud-sdk
# RUN curl -sSL https://sdk.cloud.google.com | bash
# ENV PATH $PATH:/root/google-cloud-sdk/bin

WORKDIR /app
ENV APP_WORKDIR /app

#Install python dependencies
COPY ./src/requirements* /app/
RUN pip install -r /app/requirements.dev.txt
RUN pip install -r /app/requirements_lgbm.txt